# This extends the official Langfuse docker-compose.yml with our telemetry bridge
# Usage: docker compose -f langfuse-official/docker-compose.yml -f docker-compose.langfuse.yml up

services:
  # Claude Code Telemetry Bridge
  telemetry-bridge:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    image: claude-telemetry-bridge:latest
    container_name: claude-telemetry-bridge
    depends_on:
      langfuse-web:
        condition: service_started
    ports:
      - "4318:4318"
    environment:
      # Use the auto-created Langfuse API keys
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_INIT_PROJECT_PUBLIC_KEY:-pk-lf-1234567890}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_INIT_PROJECT_SECRET_KEY:-sk-lf-1234567890}
      LANGFUSE_HOST: http://langfuse-web:3000
      LOG_LEVEL: ${LOG_LEVEL:-info}
      NODE_ENV: production
      OTLP_RECEIVER_PORT: 4318
      OTLP_RECEIVER_HOST: 0.0.0.0
      SESSION_TIMEOUT: ${SESSION_TIMEOUT:-3600000}
      MAX_REQUEST_SIZE: ${MAX_REQUEST_SIZE:-10485760}
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4318/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped