name: Changelog

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Generate changelog
        run: |
          # Install git-cliff
          curl -L https://github.com/orhun/git-cliff/releases/download/v2.0.0/git-cliff-2.0.0-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv git-cliff-2.0.0/git-cliff /usr/local/bin/
          
          # Generate changelog
          git-cliff --config .github/cliff.toml --output CHANGELOG.md --verbose
          
      - name: Check if changelog was updated
        id: git-diff
        run: |
          if git diff --exit-code CHANGELOG.md; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.git-diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update CHANGELOG.md"
          title: "chore: update CHANGELOG.md"
          body: |
            ## 📝 Automated Changelog Update
            
            This PR updates the CHANGELOG.md file with the latest commits.
            
            ### Changes Made:
            - Updated CHANGELOG.md with recent commits
            - Organized by conventional commit types
            - Added links to commits and issues
            
            ---
            *This PR was automatically generated by the changelog workflow.*
          branch: update-changelog
          delete-branch: true
          labels: |
            documentation
            automated