name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
      env:
        SKIP_INTEGRATION_TESTS: true
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Update version in files
      run: |
        # Extract version without 'v' prefix
        VERSION="${{ github.ref_name }}"
        VERSION="${VERSION#v}"
        
        # Update version badge in README
        sed -i "s|Version-[0-9.]*-blue|Version-${VERSION}-blue|g" README.md
        
        # Update version in package.json
        npm version ${VERSION} --no-git-tag-version
        
        # Commit the changes if files were modified
        if ! git diff --exit-code; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md package.json package-lock.json
          git commit -m "chore: update version to ${VERSION} [skip ci]"
          git push origin main
        fi
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ github.ref_name }}" \
          --title "Release ${{ github.ref_name }}" \
          --notes "## What's Changed
        
        See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
        
        ## Docker Image
        
        \`\`\`bash
        docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        \`\`\`
        
        ## Quick Start
        
        \`\`\`bash
        git clone https://github.com/${{ github.repository }}.git
        cd claude-code-telemetry
        ./quickstart.sh
        \`\`\`"