name: Mark stale issues and PRs

on:
  schedule:
    - cron: '30 1 * * *'  # Daily at 1:30 AM UTC
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        
        # Issue settings
        stale-issue-message: |
          👋 This issue has been automatically marked as stale because it has not had recent activity. 
          
          It will be closed in 14 days if no further activity occurs. To keep it open:
          - Comment with any updates or additional information
          - Add the `keep-open` label
          
          Thank you for your contributions to Claude Code Telemetry!
          
        close-issue-message: |
          🔒 This issue has been automatically closed due to inactivity. 
          
          If you believe this issue is still relevant:
          - Feel free to reopen it with additional context
          - Create a new issue referencing this one
          
          Thank you for your understanding!
          
        stale-issue-label: 'stale'
        days-before-issue-stale: 60
        days-before-issue-close: 14
        exempt-issue-labels: 'pinned,security,keep-open,bug,in-progress'
        
        # PR settings
        stale-pr-message: |
          👋 This pull request has been automatically marked as stale because it has not had recent activity.
          
          It will be closed in 7 days if no further activity occurs. To keep it open:
          - Push new commits
          - Comment with any updates
          - Add the `keep-open` label
          
          We appreciate your contribution!
          
        close-pr-message: |
          🔒 This pull request has been automatically closed due to inactivity.
          
          If you'd like to continue working on this:
          - Reopen the PR when you're ready to proceed
          - Create a new PR with your changes
          
          Thank you for your efforts!
          
        stale-pr-label: 'stale'
        days-before-pr-stale: 30
        days-before-pr-close: 7
        exempt-pr-labels: 'pinned,security,keep-open,work-in-progress'
        
        # Operations settings
        operations-per-run: 30
        remove-stale-when-updated: true
        debug-only: false
        ascending: false
        
        # Exempt all issues and PRs with milestones
        exempt-all-milestones: true